-- sys_user
DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_name VARCHAR(50) NOT NULL,
  sex       VARCHAR(10) NOT NULL,
  email     VARCHAR(50),
  PRIMARY KEY (id)
);

